// examples/library-mode-demo/packages/svelte/src/Button.svelte
<script lang="ts">
  import { getButtonClasses } from "@ui-kit/core"
  import type { ButtonConfig } from "@ui-kit/core"

  let { variant = "primary", size = "md", disabled = false, children }: Partial<ButtonConfig> & { children?: unknown } = $props()

  const classes = $derived(getButtonClasses({ variant, size, disabled }))
</script>

<button class={classes} {disabled}>
  {@render children?.()}
</button>

// examples/library-mode-demo/packages/vue/src/Button.vue
<script setup lang="ts">
import { computed } from "vue"
import { getButtonClasses } from "@ui-kit/core"
import type { ButtonConfig } from "@ui-kit/core"

const props = withDefaults(defineProps<Partial<ButtonConfig>>(), {
  variant: "primary",
  size: "md",
  disabled: false,
})

const classes = computed(() => getButtonClasses(props))
</script>

<template>
  <button :class="classes" :disabled="disabled">
    <slot />
  </button>
</template>
